---
version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - nc_config:/config
      - nc_data:/data
    ports:
      - ${PORT}:443
    restart: unless-stopped
    depends_on:
      - nextcloud_db
    networks:
      - internal

  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - internal

volumes:
  mariadb:
  nc_data:
  nc_config:

networks:
  internal:
    external: false